### PR TITLE
langserver.org clean up & page formatting

### PR DESCRIPTION
**Pull request by lindaxie**

### CODE REVIEW

**Comment by vincentwoo** [comment]
This PR (and https://github.com/langserver/langserver.github.io/issues/3) seem to indicate VFS is no longer a thing. Are there any updates on how to perform completions without the code being local to the machine?

**Comment by felixfbecker** [comment]
@vincentwoo The VFS extension was the predecessor of https://github.com/sourcegraph/language-server-protocol/blob/master/extension-files.md, which powers all of our language servers on sourcegraph.com. Happy to answer any questions!

**Comment by vincentwoo** [comment]
Is there still a grid of which LSP providers work with that extension?

**Comment by vincentwoo** [comment]
@felixfbecker ping!

**Comment by felixfbecker** [comment]
Right now as far as I am aware it is implemented only in all language servers maintained by Sourcegraph. If the column is helpful maybe we should add it back

cc @lindaxie

**Pull request merged**
