### PR TITLE
Add marksman LSP for markdown

### PR DESCRIPTION
**Pull request by goyalyashpal**
- destination: https://langserver.org
- @artempyanykh please help with completing features table and additional capabilities 😃

### CODE REVIEW

**Comment by jdorfman** [comment]
@goyalyashpal status?

**Comment by goyalyashpal** [comment]
hi! yeah, inwas thinking about same.

@artempyanykh are you interested in completing the feature matrix 😃 ?

**Comment by artempyanykh** [comment]
@goyalyashpal this looks pretty complete to me. Although, under "Additional capabilities" you may want to add
* Support for wiki-links,
* Table of Contents generation,
* Single-file mode.

(off the to of my head)

**Comment by goyalyashpal** [comment]
sorry. with "complete", i meant to verify for the correct ones... as i just copy pasted the data from the previous entry, not particular to the marksman.

**Comment by artempyanykh** [comment]
@goyalyashpal yeah, all the boxes are ticked correctly.

**Comment by goyalyashpal** [comment]
ohkay, thanks! 😃 

'will update the additional capabilities till weekends!

**Comment by goyalyashpal** [comment]
I think it's ready from my side. 😃

**Pull request merged**
