### PR TITLE
Add Psalm info

### PR DESCRIPTION
**Pull request by muglug**
@TysonAndre may want to add info for Phan as well

### CODE REVIEW

**Comment by TysonAndre** [comment]
https://github.com/langserver/langserver.github.io/issues/79 mentioned that - I wasn't clear on formatting requirements, etc.

Aside: Phan added support for hover/go to definition/go to type definition/complete after that issue was filed

**Comment by felixfbecker** [comment]
php-language-server executes the autoloader bundled with the language server, that’s not arbitrary code execution. Does Phan execute its own autoloader or the one by the project being analyzed?

**Comment by keegancsmith** [comment]
Closing out due to age.

**Comment by muglug** [comment]
Uh why though? Is it not applicable?

**Comment by keegancsmith** [comment]
@muglug sorry the discussion above threw me off. Is this PR in a place where it is good to merge?

**Comment by muglug** [comment]
Yes, I think so?

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
