### PR TITLE
Promote erlang_ls, update its capabilities

### PR DESCRIPTION
**Pull request by robertoaloi**

### CODE REVIEW

**Comment by robertoaloi** [comment]
Relates to erlang-ls/erlang_ls#199

**Comment by robertoaloi** [comment]
@keegancsmith It looks like you have been merging PRs in this repo lately. Any reason why this PR has been pending for so long? Do you need any modifications from our side?

**Comment by keegancsmith** [comment]
Sorry I missed this. Was out on vacation when you submitted it.

**Comment by robertoaloi** [comment]
No worries. Thanks for the help!

**Pull request merged**
