### PR TITLE
add in updated Metals information

### PR DESCRIPTION
**Pull request by ckipp01**

### CODE REVIEW

**Comment by ckipp01** [comment]
Can I get an update on this?

**Comment by keegancsmith** [comment]
@ckipp01 sorry we missed this! Do you mind rebasing / reapplying your patch on master. We did a a bit of a layout change for index.html.

**Comment by ckipp01** [comment]
> @ckipp01 sorry we missed this! Do you mind rebasing / reapplying your patch on master. We did a a bit of a layout change for index.html.

Sure no problem. Rebased.

**Comment by keegancsmith** [comment]
thanks

**Pull request merged**
